version: 39
jobs:
- name: Pull from GitHub
  steps:
  - !PullRepository
    name: pull
    remoteUrl: https://github.com/Nexirift/db
    refs: refs/heads/* refs/tags/*
    withLfs: false
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
